const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const {start}=require('./helpers.cjs');
(async()=>{
 const server=await start(),browser=await chromium.launch({channel:'chrome',headless:true}),context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.goto(server.url+'/');await page.waitForFunction(()=>!!db);
 const base64=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=320;c.height=240;const x=c.getContext('2d');x.fillStyle='#aaaaaa';x.fillRect(0,0,320,240);for(let yy=40;yy<205;yy+=12)for(let xx=88;xx<233;xx+=12){x.fillStyle=`rgb(${(xx*17+yy*5)%200},${(xx*3+yy*11)%200},${(xx*19+yy*7)%200})`;x.fillRect(xx,yy,12,12);}return c.toDataURL('image/png').split(',')[1];});
 const file={name:'fixture.png',mimeType:'image/png',buffer:Buffer.from(base64,'base64')};
 await page.click('#newArtworkBtn');await page.fill('[name="nome"]','Peça recortada');await page.fill('[name="patrimonio"]','FOCUS-01');await page.setInputFiles('#referenceInput',file);await page.waitForFunction(()=>!busy&&referenceFiles.length===1);
 const originalHash=await page.evaluate(()=>photoHash(referenceFiles[0]));
 async function select(){
  await page.waitForSelector('#focusCanvas');const b=await page.locator('#focusCanvas').boundingBox();
  await page.mouse.move(b.x+b.width*.25,b.y+b.height*.12);await page.mouse.down();await page.mouse.move(b.x+b.width*.76,b.y+b.height*.9,{steps:5});await page.mouse.up();
 }
 await page.click('#referencePreview .focus-button');await select();await page.screenshot({path:path.join(server.resultDir,'focus-mobile.png')});await page.click('#focusApply');await page.waitForSelector('#focusDialog',{state:'detached'});
 const rect=await page.evaluate(()=>referenceCrops[0]);assert(rect&&rect[2]>.5&&rect[2]<.52);
 await page.click('[type="submit"]');await page.waitForFunction(()=>!busy&&!artworkDialog.open);
 const saved=await page.evaluate(async()=>{const o=(await all('obras'))[0];return {crop:o.recortes[0],hash:await photoHash(o.fotos[0]),valid:AcervoMatcher.valid(o.descriptors[0]),originalAspect:(await createImageBitmap(o.fotos[0])).width/(await createImageBitmap(o.fotos[0])).height,descriptorAspect:o.descriptors[0].aspect};});
 assert.deepEqual(saved.crop,rect);assert.equal(saved.hash,originalHash);assert(saved.valid);assert.notEqual(saved.descriptorAspect,saved.originalAspect);console.log('PASS Referência delimitada preserva original e analisa somente o recorte');
 await page.click('.edit-art');await page.click('#existingPhotos .focus-button');await page.click('#focusReset');await page.click('#focusCancel');await page.waitForSelector('#focusDialog',{state:'detached'});await page.click('[type="submit"]');await page.waitForFunction(()=>!busy&&!artworkDialog.open);assert.deepEqual(await page.evaluate(async()=>(await all('obras'))[0].recortes[0]),rect);console.log('PASS Cancelar seleção não altera a área salva');
 await page.click('[data-view="conferir"]');await page.setInputFiles('#conferenceInput',file);await page.waitForFunction(()=>!busy&&conferenceFiles.length===1);await page.click('#conferencePreview .focus-button');await select();await page.click('#focusApply');await page.waitForSelector('#focusDialog',{state:'detached'});await page.click('#runConferenceBtn');await page.waitForFunction(()=>!busy&&resultDialog.open);
 const result=await page.evaluate(async()=>{const c=(await all('conferencias'))[0];return {crop:c.items[0].recorte,id:c.items[0].obraId,hash:await photoHash(c.items[0].foto)};});assert.deepEqual(result.crop,rect);assert.equal(result.id,1);assert.equal(result.hash,originalHash);console.log('PASS Conferência usa o recorte, armazena área e preserva foto original');
 await page.waitForFunction(()=>resultItems.querySelector('.result-item > img')?.naturalWidth>0);
 await page.screenshot({path:path.join(server.resultDir,'focus-result-mobile.png')});await page.click('[data-close="resultDialog"]');await page.click('[data-view="ajustes"]');
 const pending=page.waitForEvent('download');await page.click('#exportBtn');const download=await pending;const backup=path.join(server.resultDir,'focus-backup.json');await download.saveAs(backup);await page.setInputFiles('#importFile',backup);await page.waitForFunction(()=>!busy);
 assert.deepEqual(await page.evaluate(async()=>(await all('obras'))[0].recortes[0]),rect);assert.deepEqual(await page.evaluate(async()=>(await all('conferencias'))[0].items[0].recorte),rect);console.log('PASS Backup e restauração preservam os dois recortes');
 const invalid=await page.evaluate(async()=>{const d={version:'0.7.0',obras:[],conferencias:[{id:5,items:[{status:'pendente',recorte:[0,0,2,1]}]}]};try{await importBackup(new File([JSON.stringify(d)],'invalid.json'));return false;}catch{return (await all('obras')).length===1;}});assert(invalid);console.log('PASS Área inválida no backup é rejeitada antes de apagar dados');
 await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await context.setOffline(true);await page.reload();await page.waitForFunction(()=>!!db&&statArtworks.textContent==='1');await page.click('.edit-art');await page.click('#existingPhotos .focus-button');await page.waitForSelector('#focusCanvas');await page.click('#focusReset');await page.click('#focusApply');await page.waitForSelector('#focusDialog',{state:'detached'});await page.click('[type="submit"]');await page.waitForFunction(()=>!busy&&!artworkDialog.open);assert.equal(await page.evaluate(async()=>(await all('obras'))[0].recortes[0]),null);console.log('PASS Seleção offline e retorno à foto inteira');
 assert.deepEqual(errors,[]);await browser.close();await server.close();
})().catch(e=>{console.error(e);process.exit(1)});
